export const config = {
  title: "Cursor Saudi",
  description: "Cursor Saudi Community",
  author: "Cursor Saudi",
  /**
   * Speaker profiles. Each speaker is rendered at /speakers/{slug}/. Names that
   * appear in event frontmatter are matched against `name` and `aliases` to
   * derive talk lists. `bio`/`bioAr` are placeholders the maintainer can fill
   * in directly here. `photo` should live under /public/images/speakers/.
   */
  speakers: [
    {
      slug: "abdullah-mosaibah",
      name: "Abdullah Mosaibah",
      nameAr: "عبدالله المصيباح",
      initials: "AM",
      bio: "Software engineer based in Riyadh and an early voice in the Cursor Saudi community. Helped kick off the inaugural meetup in 2025 and returned for the Cursor Workshop in 2026 to share workflows and live demos.",
      bioAr: "مهندس برمجيات في الرياض ومن الأصوات المبكرة في مجتمع كيرسر السعودي. ساهم في إطلاق اللقاء الأول عام 2025 وعاد في ورشة كيرسر 2026 لمشاركة سير العمل والعروض الحية.",
      photo: "/images/speakers/abdullah-mosaibah.jpg",
      twitter: "https://x.com/AbdoMosaibah",
      twitterHandle: "AbdoMosaibah",
      linkedin: "https://www.linkedin.com/in/abdullah-mosaibah-67814312b/",
      aliases: [],
    },
    {
      slug: "dan-perks",
      name: "Dan Perks",
      nameAr: "دان بيركس",
      initials: "DP",
      bio: "Engineer at Cursor on the AI-native code editor, focused on support infrastructure and tooling. Joined the inaugural Cursor Saudi meetup remotely from the Cursor team to share insights and demo the editor's features for developers in Riyadh.",
      bioAr: "مهندس في كيرسر على محرر الأكواد المدعوم بالذكاء الاصطناعي، مع التركيز على البنية التحتية للدعم والأدوات. انضم إلى أول لقاء لمجتمع كيرسر السعودي عن بُعد من فريق كيرسر لمشاركة الرؤى وعرض ميزات المحرر للمطورين في الرياض.",
      photo: "/images/speakers/dan-perks.jpg",
      twitter: "https://x.com/danperks",
      twitterHandle: "danperks",
      linkedin: "https://www.linkedin.com/in/dan-perks/",
      aliases: ["Dan (Cursor)", "Dan"],
      affiliationPartnerSlug: "cursor",
    },
    {
      slug: "faris-hijazi",
      name: "Faris Hijazi",
      nameAr: "فارس حجازي",
      initials: "FH",
      bio: "Engineer focused on AI-powered product building. Led the hands-on Build Your MVP with AI session for the Cursor Saudi community in Riyadh, walking attendees through shipping a working prototype in under three hours.",
      bioAr: "مهندس مهتم ببناء المنتجات المدعومة بالذكاء الاصطناعي. قاد جلسة 'ابنِ نموذجك الأولي بالذكاء الاصطناعي' العملية لمجتمع كيرسر السعودي في الرياض، وأرشد الحضور إلى شحن نموذج أولي يعمل في أقل من ثلاث ساعات.",
      photo: "/images/speakers/faris-hijazi.jpg",
      twitter: "https://x.com/theefaris",
      twitterHandle: "theefaris",
      linkedin: "https://www.linkedin.com/in/theefaris/",
      aliases: [],
    },
    {
      slug: "usman-siddique",
      name: "Usman Siddique",
      nameAr: "عثمان صديق",
      initials: "US",
      bio: "A software engineer and AI tinkerer who's spent years building real-world products — breaking things, fixing them, and occasionally wondering why it worked in prod. Blends solid engineering fundamentals with a growing obsession for AI coding tools, helping teams ship faster and write cleaner code. At Motive he works alongside ML and R&D teams on core products used at scale.",
      bioAr: "مهندس برمجيات ومجرّب للذكاء الاصطناعي قضى سنوات في بناء منتجات حقيقية — يكسر الأشياء ويصلحها، ويتساءل أحياناً لماذا اشتغل على الإنتاج. يمزج بين الأسس الهندسية المتينة وشغف متنامٍ بأدوات البرمجة بالذكاء الاصطناعي لمساعدة الفرق على الشحن أسرع وكتابة كود أنظف. في Motive يعمل مع فرق التعلم الآلي والبحث والتطوير على منتجات أساسية تُستخدم على نطاق واسع.",
      photo: "/images/speakers/usman-siddique.jpg",
      linkedin: "https://www.linkedin.com/in/muhammmadosman/",
      aliases: [],
    },
    {
      slug: "nick-miller",
      name: "Nick Miller",
      nameAr: "نيك ميلر",
      initials: "NM",
      bio: "An architect and engineer with 25+ years of experience as a Senior Software Engineer, Product Manager, CTO, and Founder. Led specialized engineering consultancies serving global enterprises like Adobe, Amazon, and Nvidia. Currently an Engineer at Cursor, integrating large language models into production workflows.",
      bioAr: "مهندس ومعماري برمجيات بأكثر من 25 سنة خبرة بين أدوار مهندس برمجيات أول ومدير منتج ومدير تقني ومؤسس. قاد شركات استشارات هندسية متخصصة خدمت شركات عالمية مثل Adobe وAmazon وNvidia. يعمل حالياً مهندساً في كيرسر على دمج نماذج اللغة الكبيرة في سير عمل الإنتاج.",
      photo: "/images/speakers/nick-miller.jpg",
      twitter: "https://x.com/nickwm",
      twitterHandle: "nickwm",
      aliases: [],
      affiliationPartnerSlug: "cursor",
    },
  ],
  ambassadors: [
    {
      name: "Mazen Alotaibi",
      nameAr: "مازن العتيبي",
      role: "Cursor Saudi Leader",
      roleAr: "قائد كيرسر السعودية",
      city: "Riyadh",
      cityAr: "الرياض",
      photo: "/images/team/mazen.jpg",
      description: "AI Staff Engineer @ deep.sa and PyTorch Ambassador 2023 winner with ~8 years across AI research and production engineering — building models and shipping products.",
      descriptionAr: "مهندس ذكاء اصطناعي رئيسي في deep.sa وفائز ببرنامج سفراء PyTorch 2023، بخبرة تقارب 8 سنوات في أبحاث وهندسة الذكاء الاصطناعي للإنتاج — بناء نماذج وشحن منتجات",
      email: "hello@cursorsaudi.com",
      twitter: "https://x.com/ma7dev",
      twitterHandle: "ma7dev",
      linkedin: "https://www.linkedin.com/in/ma7dev/",
    },
    {
      name: "Ali Almohammed",
      nameAr: "علي المحمد",
      role: "Ambassador",
      roleAr: "سفير",
      city: "Jeddah",
      cityAr: "جدة",
      photo: "/images/team/ali-almohammed.png",
      description: "Founder & CEO at CranL, tech entrepreneur who focuses on building special and innovative solutions since 2020. Intersted in cloud, hosting, AI infrence and infrastructure.",
      descriptionAr: "مؤسس ورئيس تنفيذي لـ CranL، مؤسس تقني مهتم ببناء حلول خاصة ومبتكرة منذ عام 2020. مهتم بالسحابة والاستضافة والذكاء الاصطناعي والبنية التحتية.",
      twitter: "https://x.com/Hajajn200",
      twitterHandle: "Hajajn200",
      linkedin: "https://www.linkedin.com/in/ali-hajem-8a4734395/",
    },
    {
      name: "Faris Hijazi",
      nameAr: "فارس حجازي",
      role: "Team Member",
      roleAr: "عضو فريق",
      city: "Riyadh",
      cityAr: "الرياض",
      photo: "/images/speakers/faris-hijazi.jpg",
      description: "Engineer focused on AI-powered product building. Supports Cursor Saudi by helping run Cafe Cursor activities and community sessions in Riyadh.",
      descriptionAr: "مهندس مهتم ببناء المنتجات المدعومة بالذكاء الاصطناعي. يدعم كيرسر السعودية من خلال المساعدة في تنظيم فعاليات كافيه كيرسر والجلسات المجتمعية في الرياض.",
      twitter: "https://x.com/theefaris",
      twitterHandle: "theefaris",
      linkedin: "https://www.linkedin.com/in/theefaris/",
    },
    {
      name: "Abdullah Mosaibah",
      nameAr: "عبدالله المصيباح",
      role: "Team Member",
      roleAr: "عضو فريق",
      city: "Riyadh",
      cityAr: "الرياض",
      photo: "/images/speakers/abdullah-mosaibah.jpg",
      description:
        "Software engineer based in Riyadh and an early voice in the Cursor Saudi community. Helped kick off the inaugural meetup in 2025 and returned for the Cursor Workshop in 2026 to share workflows and live demos.",
      descriptionAr:
        "مهندس برمجيات في الرياض ومن الأصوات المبكرة في مجتمع كيرسر السعودي. ساهم في إطلاق اللقاء الأول عام 2025 وعاد في ورشة كيرسر 2026 لمشاركة سير العمل والعروض الحية.",
      twitter: "https://x.com/AbdoMosaibah",
      twitterHandle: "AbdoMosaibah",
      linkedin: "https://www.linkedin.com/in/abdullah-mosaibah-67814312b/",
    },
    {
      name: "Abdulaziz AlMushdaq",
      nameAr: "عبدالعزيز المشدق",
      role: "Team Member",
      roleAr: "عضو فريق",
      city: "Riyadh",
      cityAr: "الرياض",
      photo: "/images/team/abdulaziz-almushdaq.jpg",
      description:
        "I'm a Data and AI Engineer and tech content creator with a deep passion for everything data-related. Data Engineer at Rkiza. Supports Cursor Saudi social media and marketing efforts.",
      descriptionAr:
        "أعمل كمهندس بيانات وذكاء اصطناعي ومنشئ محتوى تقني، ولدي شغف كبير بكل ما يتعلق بالبيانات. مهندس بيانات في Rkiza. يدعم كيرسر السعودية في جهود وسائل التواصل الاجتماعي والتسويق.",
      twitter: "https://x.com/Al_Mushdaq",
      twitterHandle: "Al_Mushdaq",
      linkedin: "https://www.linkedin.com/in/almushdaq/",
    },
    {
      name: "Abdulhakeem Almidan",
      nameAr: "عبدالحكيم الميدان",
      role: "Ambassador",
      roleAr: "سفير",
      city: "Khobar",
      cityAr: "الخبر",
      photo: "/images/team/abdulhakeem.jpg",
      description: "Former Khobar chapter ambassador who helped bring Cursor events to the Eastern Province.",
      descriptionAr: "سفير فرع الخبر السابق الذي ساهم في إقامة فعاليات كيرسر في المنطقة الشرقية.",
      twitter: "https://x.com/abdulhakeem_mdn",
      linkedin: "https://www.linkedin.com/in/abdulhakeem-almidan/",
      status: "retired",
    },
  ],
  /**
   * Individuals who help make Cursor Saudi events happen in non-speaker,
   * non-ambassador ways (e.g. sending merch, on-site logistics, photography
   * coordination). Rendered in the "Supporters" section of the Thank You page.
   * `affiliation` should be a partner slug from `partners` below — used to
   * group/badge supporters by the org they're affiliated with.
   */
  supporters: [
    {
      name: "Ben Lang",
      nameAr: "بن لانغ",
      role: "Community Lead",
      roleAr: "قائد المجتمع",
      contribution: "Main point of contact from the Cursor team. Helps make our events happen and connects us to the broader Cursor ecosystem.",
      contributionAr: "نقطة التواصل الرئيسية من فريق كيرسر. يساعد على إقامة فعالياتنا ويربطنا بمنظومة كيرسر الأوسع.",
      twitter: "https://x.com/benln",
      twitterHandle: "benln",
      linkedin: "https://www.linkedin.com/in/benmlang/",
      photo: "/images/partners/cursor/ben-lang.jpg",
      affiliation: "cursor",
    },
    {
      name: "Sunita Rao",
      nameAr: "سونيتا راو",
      role: "Community Supporter",
      roleAr: "داعمة للمجتمع",
      contribution: "Supports Cursor Saudi from the Cursor team and helps make our events happen.",
      contributionAr: "تدعم كيرسر السعودية من فريق كيرسر وتساعد على إقامة فعالياتنا.",
      twitter: "https://x.com/sunrao",
      twitterHandle: "sunrao",
      linkedin: "https://www.linkedin.com/in/sunrao/",
      photo: "/images/partners/cursor/sunita-rao.jpg",
      affiliation: "cursor",
    },
    {
      name: "Fawziyah Nabeelah",
      nameAr: "فوزية نبيلة",
      role: "Community Supporter",
      roleAr: "داعمة للمجتمع",
      contribution: "Sends Cursor merch and helps make our events happen.",
      contributionAr: "ترسل هدايا كيرسر وتساعد على إقامة فعالياتنا.",
      twitter: "https://x.com/ftnabeelah",
      twitterHandle: "ftnabeelah",
      linkedin: "https://www.linkedin.com/in/fawziyahnabeelah/",
      photo: "/images/partners/cursor/fawziyah-nabeelah.jpg",
      affiliation: "cursor",
    },
  ],
  /**
   * Invitations from external organizations for community members to speak or
   * participate in their events. Rendered on the Events page.
   */
  invites: [
    {
      slug: "hackathonat-ai-game-jam",
      type: "panel",
      speaker: "Mazen Alotaibi",
      speakerAr: "مازن العتيبي",
      talkTitle: "Introduction to AI Tools for Game Developers",
      talkTitleAr: "مقدمة في أدوات الذكاء الاصطناعي لمطوري الألعاب",
      invitedBy: "Hackathonat",
      invitedByAr: "هاكاثونات",
      invitedByUrl: "https://x.com/hackathonat",
      invitedByLogo: "/images/invites/hackathonat.jpg",
      postUrl: "https://x.com/hackathonat/status/1987605905630777367",
      date: "2025-07-05",
      slides: ["https://github.com/cursorsaudi/events-slides/blob/main/2025-11-riyadh-ai-game.pdf"],
      photos: ["/invites/hackathonat-ai-game-jam.jpg"],
    },
    {
      slug: "sahel-mahdi-ai-tools",
      type: "interview",
      speaker: "Mazen Alotaibi",
      speakerAr: "مازن العتيبي",
      talkTitle: "AI Tools and Cursor",
      talkTitleAr: "أدوات الذكاء الاصطناعي وكيرسر",
      invitedBy: "Sahel Mahdi",
      invitedByAr: "سهل مهدي",
      invitedByUrl: "https://x.com/Sahelmahdi",
      invitedByLogo: "/images/invites/sahel-mahdi.jpg",
      postUrl: "https://x.com/Sahelmahdi/status/2016528155645804670",
      recordingUrl: "https://www.youtube.com/watch?v=L435AAiRvXY",
      date: "2026-02-15",
      photos: ["/invites/sahel-mahdi-interview.png"],
    },
    {
      slug: "e3-ventures-mvp",
      type: "interview",
      speaker: "Mazen Alotaibi",
      speakerAr: "مازن العتيبي",
      talkTitle: "Build MVP Without Coding",
      talkTitleAr: "ابنِ نموذجك الأولي بدون برمجة",
      invitedBy: "E3 Ventures",
      invitedByAr: "E3 Ventures",
      invitedByUrl: "https://x.com/e3ventures",
      invitedByLogo: "/images/invites/e3-ventures.jpg",
      postUrl: "https://x.com/e3ventures/status/1923421103038341442",
      date: "2025-05-17",
      photos: ["/invites/e3-ventures-mvp-talk.jpg"],
    },
    {
      slug: "dal-health-datathon",
      type: "talk",
      speaker: "Mazen Alotaibi",
      speakerAr: "مازن العتيبي",
      talkTitle: "Introduction to Cursor at the Health Datathon",
      talkTitleAr: "مقدمة عن كيرسر في الداتاثون الصحي",
      invitedBy: "DAL Organization",
      invitedByAr: "جمعية دال",
      invitedByUrl: "/partners/dal/",
      invitedByLogo: "/logos/dal.png",
      postUrl: "https://x.com/cursorsaudi/status/1849101987507462406",
      date: "2025-10-24",
      slides: ["https://github.com/cursorsaudi/events-slides/blob/main/2025-10-riyadh-hackathon.pdf"],
      photos: [
        "/invites/health-datathon/01-mazen-presenting.jpg",
        "/invites/health-datathon/02-ai-coding-tools-slide.jpg",
        "/invites/health-datathon/03-participants-chatting.jpg",
        "/invites/health-datathon/04-participant-working.jpg",
        "/invites/health-datathon/05-participant-focused.jpg",
        "/invites/health-datathon/06-venue-entrance.jpg",
      ],
    },
  ],
  social: {
    luma: "https://lu.ma/cursor-saudi",
    discord: "https://discord.gg/KpsKtegvz4",
    twitter: "https://x.com/cursorsaudi",
    /** Community X handle without @ (for display copy). */
    twitterHandle: "cursorsaudi",
    email: "hello@cursorsaudi.com",
    github: "https://github.com/cursorsaudi",
  },
  /**
   * Partner profiles. Each partner is rendered at /partners/{slug}/. The set of
   * events a partner was part of is the union of:
   *   - events whose `venue` frontmatter matches any string in `eventVenues`
   *   - events whose ID is listed in `events`
   * Use `eventVenues` for venue hosts and `events` for community partners.
   */
  partners: [
    {
      slug: "cursor",
      name: "Cursor",
      nameAr: "كيرسر",
      role: "official",
      logo: "/logos/cursor.svg",
      url: "https://cursor.com",
      description:
        "The AI-native code editor from Anysphere — built on VS Code with autocomplete, chat, and agent-style workflows so developers ship faster.",
      descriptionAr:
        "محرر أكواد مدعوم بالذكاء الاصطناعي من Anysphere — مبني على VS Code مع إكمال ذكي ودردشة وسير عمل وكيلي لمساعدة المطورين على الشحن بسرعة أكبر.",
      cities: [],
      eventVenues: [],
      events: [],
      omitEventStats: true,
      parentCompany: {
        name: "Anysphere",
        nameAr: "Anysphere",
        url: "https://anysphere.inc",
      },
      detailParagraphs: {
        en: [
          "Anysphere is the company behind Cursor. The team builds AI-native developer tools with a focus on real production workflows — not demos — so you can refactor, navigate large codebases, and pair with models inside the editor you already use.",
          "As Cursor Saudi’s official partner, Cursor supports the community through team talks, workshops, and product access. Community meetups and hackathons are organized locally; Cursor is the global product and team that backs the ecosystem.",
        ],
        ar: [
          "Anysphere هي الشركة التي تطوّر كيرسر. الفريق يبني أدوات للمطورين مدعومة بالذكاء الاصطناعي مع تركيز على سير عمل الإنتاج الفعلي — لا مجرد عروض — لإعادة هيكلة الكود والتنقل في مشاريع كبيرة والعمل مع النماذج داخل المحرر الذي تعتمد عليه أصلاً.",
          "كشريك رسمي لـ كيرسر السعودية، تدعم كيرسر المجتمع من خلال جلسات الفريق وورش العمل والوصول للمنتج. اللقاءات والهاكاثونات تُنظَّم محلياً؛ كيرسر هو المنتج والفريق العالمي الذي يدعم المنظومة.",
        ],
      },
      contributors: [],
    },
    {
      slug: "dal",
      name: "Dal Organization",
      nameAr: "جمعية دال",
      role: "community-partner",
      logo: "/logos/dal.png",
      url: "https://linktr.ee/DalData",
      description:
        "A Saudi nonprofit empowering data science & AI enthusiasts through hands-on programs, datathons, and job-shadowing. Supported and funded by Misk Foundation and SDAIA.",
      descriptionAr:
        "جمعية غير ربحية سعودية تمكّن المهتمين بعلوم البيانات والذكاء الاصطناعي من خلال برامج عملية وداتاثونات. مدعومة وممولة من مؤسسة مسك وسدايا.",
      cities: ["Riyadh"],
      eventVenues: [],
      events: [
        "2025-12-25-contributing-to-open-source-with-cursor",
        "2026-01-10-the-ai-dev-stack-with-cursor",
        "2026-03-07-cursor-workshop-ship-in-3-hours",
      ],
      contributors: [
        {
          name: "Ghadah Alhabib",
          nameAr: "غادة الحبيب",
          role: "Cofounder & CEO",
          roleAr: "شريكة مؤسسة ورئيسة تنفيذية",
          linkedin: "https://www.linkedin.com/in/ghadah-alhabib/",
          twitterHandle: "ghadah_alha",
          photo: "/images/partners/dal/ghadah-alhabib.jpg",
        },
        {
          name: "Yazeed Alshalani",
          nameAr: "يزيد الشعلاني",
          role: "Cofounder",
          roleAr: "شريك مؤسس",
          linkedin: "https://www.linkedin.com/in/yazeed-alshalani/",
          twitterHandle: "YazeedShalani",
          photo: "/images/partners/dal/yazeed-alshalani.jpg",
        },
        {
          name: "Basil Mahmoud",
          nameAr: "باسل محمود",
          role: "Cofounder",
          roleAr: "شريك مؤسس",
          linkedin: "https://www.linkedin.com/in/basil-mahmoud/",
          photo: "/images/partners/dal/basil-mahmoud.jpg",
        },
        {
          name: "Islam Alharbi",
          nameAr: "إسلام الحربي",
          role: "Marketing Manager",
          roleAr: "مديرة تسويق",
          linkedin: "https://www.linkedin.com/in/islam-alharbi/",
          photo: "/images/partners/dal/islam-alharbi.jpg",
        },
        {
          name: "Maan Albader",
          nameAr: "معن البدر",
          role: "Project Manager",
          roleAr: "مدير مشروع",
          linkedin: "https://www.linkedin.com/in/maanalbader/",
          photo: "/images/partners/dal/maan-albader.jpg",
        },
        {
          name: "Abdullah Alshowaier",
          nameAr: "عبدالله الشويعر",
          role: "Project Manager",
          roleAr: "مدير مشروع",
          linkedin: "https://www.linkedin.com/in/abdullah-alshowaier-/",
          photo: "/images/partners/dal/abdullah-alshowaier.jpg",
        },
        {
          name: "Reema Altwuaijri",
          nameAr: "ريما التويجري",
          role: "Partnership Manager",
          roleAr: "مدير شراكات",
          linkedin: "https://www.linkedin.com/in/reemaft/",
          photo: "/images/partners/dal/reema-altwuaijri.jpg",
        },
        {
          name: "Hanouf Almogri",
          nameAr: "الهنوف المقري",
          role: "Operations Manager",
          roleAr: "مديرة عمليات",
          linkedin: "https://www.linkedin.com/in/hanouf-almogri/",
          photo: "/images/partners/dal/hanouf-almogri.jpg",
        },
        {
          name: "Raghad Alshathri",
          nameAr: "رغد الشثري",
          role: "Photographer",
          roleAr: "مصورة",
          twitter: "https://x.com/1sRaghad",
          twitterHandle: "1sRaghad",
          photo: "/images/partners/dal/raghad-alshathri.jpg",
        },
        {
          name: "Alanoud Alghayth",
          nameAr: "العنود آل غيث",
          role: "Project Manager",
          roleAr: "مديرة مشروع",
          linkedin: "https://www.linkedin.com/in/alanoud-alghayth/",
          photo: "/images/partners/dal/alanoud-alghayth.jpeg",
        },
      ],
    },
    {
      slug: "mozn",
      name: "Mozn",
      nameAr: "مزن",
      role: "venue-host",
      logo: "/logos/mozn.svg",
      url: "https://mozn.ai",
      description:
        "Saudi AI company building enterprise AI products for the Arabic-first market, including NLP, risk, and compliance solutions.",
      descriptionAr:
        "شركة ذكاء اصطناعي سعودية تبني منتجات ذكاء اصطناعي للمؤسسات في السوق العربي، تشمل حلول معالجة اللغة والمخاطر والامتثال.",
      cities: ["Riyadh"],
      eventVenues: ["Mozn Office"],
      events: [],
    },
    {
      slug: "code",
      name: "CODE",
      nameAr: "مركز ريادة الأعمال الرقمية",
      role: "venue-host",
      logo: "/logos/code.svg",
      url: "https://code.mcit.gov.sa/en",
      description:
        "Center of Digital Entrepreneurship by MCIT — coworking spaces, business services, and acceleration programs supporting digital startups.",
      descriptionAr:
        "مركز ريادة الأعمال الرقمية التابع لوزارة الاتصالات — مساحات عمل مشتركة وخدمات أعمال وبرامج تسريع لدعم الشركات الرقمية الناشئة.",
      cities: ["Riyadh"],
      eventVenues: ["CODE"],
      events: [],
    },
    {
      slug: "monshaat",
      name: "Monshaat",
      nameAr: "منشآت",
      role: "venue-host",
      logo: "/logos/monshaat-dark.svg",
      url: "https://www.monshaat.gov.sa/ar/ssc",
      description:
        "SME support centers by Monshaat — providing training, mentorship, consulting, and coworking spaces for entrepreneurs across Saudi Arabia.",
      descriptionAr:
        "مراكز دعم المنشآت — تقدم التدريب والإرشاد والاستشارات ومساحات العمل المشتركة لرواد الأعمال في السعودية.",
      cities: ["Khobar"],
      eventVenues: ["Khobar Tech Hub"],
      events: [],
    },
    {
      slug: "nauatech",
      name: "Nauatech",
      nameAr: "نواتك",
      role: "past-community-partner",
      logo: "/logos/nauatech.svg",
      url: "https://naua.tech/",
      description:
        "A Saudi tech community that partnered with Cursor Saudi for the community kickoff in Riyadh.",
      descriptionAr:
        "مجتمع تقني سعودي شارك في دعم حفل إطلاق مجتمع كيرسر السعودية في الرياض.",
      cities: ["Riyadh"],
      eventVenues: [],
      events: ["2025-05-28-kickoff"],
      contributors: [
        {
          name: "Reda Banjar",
          nameAr: "رضا بنجر",
          role: "Founder & CEO",
          roleAr: "مؤسس ورئيس تنفيذي",
          twitter: "https://x.com/RedaBanjar",
          twitterHandle: "RedaBanjar",
          photo: "/images/partners/nauatech/reda-banjar.jpg",
        },
      ],
    },
  ],
} as const;
