export const config = {
  title: "Cursor Türkiye",
  description: "Cursor Türkiye Community",
  author: "Cursor Türkiye",
  /**
   * Speaker profiles. Each speaker is rendered at /speakers/{slug}/. Names that
   * appear in event frontmatter are matched against `name` and `aliases` to
   * derive talk lists. `bio`/`bioTr` are placeholders the maintainer can fill
   * in directly here. `photo` should live under /public/images/speakers/.
   */
  speakers: [
    {
      slug: "dan-perks",
      name: "Dan Perks",
      nameTr: "Dan Perks",
      initials: "DP",
      bio: "Engineer at Cursor on the AI-native code editor, focused on support infrastructure and tooling. Joined the inaugural Cursor Türkiye meetup remotely from the Cursor team to share insights and demo the editor's features for developers in Ankara.",
      bioTr: "Engineer at Cursor on the AI-native code editor, focused on support infrastructure and tooling. Joined the inaugural Cursor Türkiye meetup remotely from the Cursor team to share insights and demo the editor's features for developers in Ankara.",
      photo: "/images/speakers/dan-perks.jpg",
      twitter: "https://x.com/danperks",
      twitterHandle: "danperks",
      linkedin: "https://www.linkedin.com/in/dan-perks/",
      aliases: ["Dan (Cursor)", "Dan"],
      affiliationPartnerSlug: "cursor",
    },
    {
      slug: "usman-siddique",
      name: "Usman Siddique",
      nameTr: "Usman Siddique",
      initials: "US",
      bio: "A software engineer and AI tinkerer who's spent years building real-world products — breaking things, fixing them, and occasionally wondering why it worked in prod. Blends solid engineering fundamentals with a growing obsession for AI coding tools, helping teams ship faster and write cleaner code. At Motive he works alongside ML and R&D teams on core products used at scale.",
      bioTr: "A software engineer and AI tinkerer who's spent years building real-world products — breaking things, fixing them, and occasionally wondering why it worked in prod. Blends solid engineering fundamentals with a growing obsession for AI coding tools, helping teams ship faster and write cleaner code. At Motive he works alongside ML and R&D teams on core products used at scale.",
      photo: "/images/speakers/usman-siddique.jpg",
      linkedin: "https://www.linkedin.com/in/muhammmadosman/",
      aliases: [],
    },
    {
      slug: "nick-miller",
      name: "Nick Miller",
      nameTr: "Nick Miller",
      initials: "NM",
      bio: "An architect and engineer with 25+ years of experience as a Senior Software Engineer, Product Manager, CTO, and Founder. Led specialized engineering consultancies serving global enterprises like Adobe, Amazon, and Nvidia. Currently an Engineer at Cursor, integrating large language models into production workflows.",
      bioTr: "An architect and engineer with 25+ years of experience as a Senior Software Engineer, Product Manager, CTO, and Founder. Led specialized engineering consultancies serving global enterprises like Adobe, Amazon, and Nvidia. Currently an Engineer at Cursor, integrating large language models into production workflows.",
      photo: "/images/speakers/nick-miller.jpg",
      twitter: "https://x.com/nickwm",
      twitterHandle: "nickwm",
      aliases: [],
      affiliationPartnerSlug: "cursor",
    },
  ],
  ambassadors: [
    {
      name: "Emre Özcan",
      nameTr: "Emre Özcan",
      role: "Cursor Ankara Ambassador",
      roleTr: "Cursor Ankara Ambassador",
      city: "Ankara",
      cityTr: "Ankara",
      photo: "/images/team/emre.jfif",
      description: "Computer Engineer and Android Engineer with over 5 years of experience building scalable mobile applications across the fintech, defense, logistics, and insurance sectors.",
      descriptionTr: "Fintek, savunma, lojistik ve sigorta sektörlerinde ölçeklenebilir mobil uygulamalar geliştiren, 5+ yıllık deneyime sahip Bilgisayar ve Android Mühendisi.",
      email: "hello@cursorturkiye.com",
      twitter: "https://x.com/buildermare",
      twitterHandle: "buildermare",
      linkedin: "https://www.linkedin.com/in/emre-%C3%B6zcan-6aa582193/",
    },
    {
      name: "Khaled Bahabri",
      nameTr: "Khaled Bahabri",
      role: "Cursor Izmir Ambassador",
      roleTr: "Cursor İzmir Elçisi",
      city: "Izmir",
      cityTr: "İzmir",
      photo: "/images/team/khaled.jfif",
      description: "Mechatronics Engineering student, Falcons UAV team management member, and software developer.",
      descriptionTr: "Mekatronik Mühendisliği öğrencisi, Falcons UAV takımında yönetim üyesi ve yazılım geliştirici.",
      twitter: "https://x.com/khaledbuilds",
      twitterHandle: "khaledbuilds",
      linkedin: "https://www.linkedin.com/in/khaledbuilds/",
    },
    {
      name: "Ozgur Unlu",
      nameTr: "Ozgur Unlu",
      role: "Cursor Istanbul Ambassador",
      roleTr: "Cursor İstanbul Elçisi",
      city: "Istanbul",
      cityTr: "İstanbul",
      photo: "/images/team/ozgur.png",
      description: "CMO @ Stonki.ai, Ex-CMO Amazon TR, Google Alum, Ex-VP HSBC || Marketing / AI / Product / Finance | | Bridging AI, Marketing, and Innovation",
      descriptionTr: "Stonki.ai'de CMO, eski Amazon TR CMO'su, Google mezunu, eski HSBC VP'si || Pazarlama / AI / Ürün / Finans || AI, pazarlama ve inovasyon arasında köprü kuruyor.",
      twitter: "https://x.com/ozgurunlu",
      twitterHandle: "ozgurunlu",
      linkedin: "https://www.linkedin.com/in/thisisozgur/",
    },
  ],
  /**
   * Individuals who help make Cursor Türkiye events happen in non-speaker,
   * non-ambassador ways (e.g. sending merch, on-site logistics, photography
   * coordination). Rendered in the "Supporters" section of the Thank You page.
   * `affiliation` should be a partner slug from `partners` below — used to
   * group/badge supporters by the org they're affiliated with.
   */
  supporters: [
    {
      name: "Ben Lang",
      nameTr: "Ben Lang",
      role: "Community Lead",
      roleTr: "Community Lead",
      contribution: "Main point of contact from the Cursor team. Helps make our events happen and connects us to the broader Cursor ecosystem.",
      contributionTr: "Main point of contact from the Cursor team. Helps make our events happen and connects us to the broader Cursor ecosystem.",
      twitter: "https://x.com/benln",
      twitterHandle: "benln",
      linkedin: "https://www.linkedin.com/in/benmlang/",
      photo: "/images/partners/cursor/ben-lang.jpg",
      affiliation: "cursor",
    },
    {
      name: "Sunita Rao",
      nameTr: "Sunita Rao",
      role: "Community Supporter",
      roleTr: "Community Supporter",
      contribution: "Supports Cursor Türkiye from the Cursor team and helps make our events happen.",
      contributionTr: "Supports Cursor Türkiye from the Cursor team and helps make our events happen.",
      twitter: "https://x.com/sunrao",
      twitterHandle: "sunrao",
      linkedin: "https://www.linkedin.com/in/sunrao/",
      photo: "/images/partners/cursor/sunita-rao.jpg",
      affiliation: "cursor",
    },
    {
      name: "Fawziyah Nabeelah",
      nameTr: "Fawziyah Nabeelah",
      role: "Community Supporter",
      roleTr: "Community Supporter",
      contribution: "Sends Cursor merch and helps make our events happen.",
      contributionTr: "Sends Cursor merch and helps make our events happen.",
      twitter: "https://x.com/ftnabeelah",
      twitterHandle: "ftnabeelah",
      linkedin: "https://www.linkedin.com/in/fawziyahnabeelah/",
      photo: "/images/partners/cursor/fawziyah-nabeelah.jpg",
      affiliation: "cursor",
    },
  ],
  /**
   * Invitations from external organizations for community members to speak or
   * participate in their events. Rendered on the Events page.
   */
  invites: [
    {
      slug: "hackathonat-ai-game-jam",
      type: "panel",
      speaker: "Emre Özcan",
      speakerTr: "Türkçe Türkçe",
      talkTitle: "Introduction to AI Tools for Game Developers",
      talkTitleTr: "Introduction to AI Tools for Game Developers",
      invitedBy: "Hackathonat",
      invitedByTr: "Hackathonat",
      invitedByUrl: "https://x.com/hackathonat",
      invitedByLogo: "/images/invites/hackathonat.jpg",
      postUrl: "https://x.com/hackathonat/status/1987605905630777367",
      date: "2025-07-05",
      slides: ["https://github.com/cursorturkiye/events-slides/blob/main/2025-11-riyadh-ai-game.pdf"],
      photos: ["/invites/hackathonat-ai-game-jam.jpg"],
    },
    {
      slug: "sahel-mahdi-ai-tools",
      type: "interview",
      speaker: "Emre Özcan",
      speakerTr: "Türkçe Türkçe",
      talkTitle: "AI Tools and Cursor",
      talkTitleTr: "AI Tools and Cursor",
      invitedBy: "Sahel Mahdi",
      invitedByTr: "Sahel Mahdi",
      invitedByUrl: "https://x.com/Sahelmahdi",
      invitedByLogo: "/images/invites/sahel-mahdi.jpg",
      postUrl: "https://x.com/Sahelmahdi/status/2016528155645804670",
      recordingUrl: "https://www.youtube.com/watch?v=L435AAiRvXY",
      date: "2026-02-15",
      photos: ["/invites/sahel-mahdi-interview.png"],
    },
    {
      slug: "e3-ventures-mvp",
      type: "interview",
      speaker: "Emre Özcan",
      speakerTr: "Türkçe Türkçe",
      talkTitle: "Build MVP Without Coding",
      talkTitleTr: "Build MVP Without Coding",
      invitedBy: "E3 Ventures",
      invitedByTr: "E3 Ventures",
      invitedByUrl: "https://x.com/e3ventures",
      invitedByLogo: "/images/invites/e3-ventures.jpg",
      postUrl: "https://x.com/e3ventures/status/1923421103038341442",
      date: "2025-05-17",
      photos: ["/invites/e3-ventures-mvp-talk.jpg"],
    },
    {
      slug: "dal-health-datathon",
      type: "talk",
      speaker: "Emre Özcan",
      speakerTr: "Türkçe Türkçe",
      talkTitle: "Introduction to Cursor at the Health Datathon",
      talkTitleTr: "Introduction to Cursor at the Health Datathon",
      invitedBy: "DAL Organization",
      invitedByTr: "DAL Organization",
      invitedByUrl: "/partners/dal/",
      invitedByLogo: "/logos/dal.png",
      postUrl: "https://x.com/cursorturkiye/status/1849101987507462406",
      date: "2025-10-24",
      slides: ["https://github.com/cursorturkiye/events-slides/blob/main/2025-10-riyadh-hackathon.pdf"],
      photos: [
        "/invites/health-datathon/01-mazen-presenting.jpg",
        "/invites/health-datathon/02-ai-coding-tools-slide.jpg",
        "/invites/health-datathon/03-participants-chatting.jpg",
        "/invites/health-datathon/04-participant-working.jpg",
        "/invites/health-datathon/05-participant-focused.jpg",
        "/invites/health-datathon/06-venue-entrance.jpg",
      ],
    },
  ],
  social: {
    luma: "https://lu.ma/cursor-saudi",
    discord: "https://discord.gg/KpsKtegvz4",
    twitter: "https://x.com/cursorturkiye",
    /** Community X handle without @ (for display copy). */
    twitterHandle: "cursorturkiye",
    email: "hello@cursorturkiye.com",
    github: "https://github.com/cursorturkiye",
  },
  /**
   * Partner profiles. Each partner is rendered at /partners/{slug}/. The set of
   * events a partner was part of is the union of:
   *   - events whose `venue` frontmatter matches any string in `eventVenues`
   *   - events whose ID is listed in `events`
   * Use `eventVenues` for venue hosts and `events` for community partners.
   */
  partners: [
    {
      slug: "cursor",
      name: "Cursor",
      nameTr: "Cursor",
      role: "official",
      logo: "/logos/cursor.svg",
      url: "https://cursor.com",
      description:
        "The AI-native code editor from Anysphere — built on VS Code with autocomplete, chat, and agent-style workflows so developers ship faster.",
      descriptionTr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Anysphere — Türkçe Türkçe VS Code Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: [],
      eventVenues: [],
      events: [],
      omitEventStats: true,
      parentCompany: {
        name: "Anysphere",
        nameTr: "Anysphere",
        url: "https://anysphere.inc",
      },
      detailParagraphs: {
        en: [
          "Anysphere is the company behind Cursor. The team builds AI-native developer tools with a focus on real production workflows — not demos — so you can refactor, navigate large codebases, and pair with models inside the editor you already use.",
          "As Cursor Türkiye’s official partner, Cursor supports the community through team talks, workshops, and product access. Community meetups and hackathons are organized locally; Cursor is the global product and team that backs the ecosystem.",
        ],
        ar: [
          "Anysphere Türkçe Türkçe Türkçe Türkçe Cursor. Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
          "TürkçeResmi Is Ortagi Türkçe Cursor TürkiyeTürkçe Türkçe Cursor Topluluk Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe. Türkçe Türkçe Türkçe Türkçe Cursor Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
        ],
      },
      contributors: [],
    },
    {
      slug: "dal",
      name: "Dal Organization",
      nameTr: "Dal Organization",
      role: "community-partner",
      logo: "/logos/dal.png",
      url: "https://linktr.ee/DalData",
      description:
        "A Türkiye nonprofit empowering data science & AI enthusiasts through hands-on programs, datathons, and job-shadowing. Supported and funded by Misk Foundation and SDAIA.",
      descriptionTr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe. Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Ankara"],
      eventVenues: [],
      events: [
        "2025-12-25-contributing-to-open-source-with-cursor",
        "2026-01-10-the-ai-dev-stack-with-cursor",
        "2026-03-07-cursor-workshop-ship-in-3-hours",
      ],
      contributors: [
        {
          name: "Ghadah Alhabib",
          nameTr: "Ghadah Alhabib",
          role: "Cofounder & CEO",
          roleTr: "Cofounder & CEO",
          linkedin: "https://www.linkedin.com/in/ghadah-alhabib/",
          twitterHandle: "ghadah_alha",
          photo: "/images/partners/dal/ghadah-alhabib.jpg",
        },
        {
          name: "Yazeed Alshalani",
          nameTr: "Yazeed Alshalani",
          role: "Cofounder",
          roleTr: "Cofounder",
          linkedin: "https://www.linkedin.com/in/yazeed-alshalani/",
          twitterHandle: "YazeedShalani",
          photo: "/images/partners/dal/yazeed-alshalani.jpg",
        },
        {
          name: "Basil Mahmoud",
          nameTr: "Basil Mahmoud",
          role: "Cofounder",
          roleTr: "Cofounder",
          linkedin: "https://www.linkedin.com/in/basil-mahmoud/",
          photo: "/images/partners/dal/basil-mahmoud.jpg",
        },
        {
          name: "Islam Alharbi",
          nameTr: "Islam Alharbi",
          role: "Marketing Manager",
          roleTr: "Marketing Manager",
          linkedin: "https://www.linkedin.com/in/islam-alharbi/",
          photo: "/images/partners/dal/islam-alharbi.jpg",
        },
        {
          name: "Maan Albader",
          nameTr: "Maan Albader",
          role: "Project Manager",
          roleTr: "Project Manager",
          linkedin: "https://www.linkedin.com/in/maanalbader/",
          photo: "/images/partners/dal/maan-albader.jpg",
        },
        {
          name: "Abdullah Alshowaier",
          nameTr: "Abdullah Alshowaier",
          role: "Project Manager",
          roleTr: "Project Manager",
          linkedin: "https://www.linkedin.com/in/abdullah-alshowaier-/",
          photo: "/images/partners/dal/abdullah-alshowaier.jpg",
        },
        {
          name: "Reema Altwuaijri",
          nameTr: "Reema Altwuaijri",
          role: "Partnership Manager",
          roleTr: "Partnership Manager",
          linkedin: "https://www.linkedin.com/in/reemaft/",
          photo: "/images/partners/dal/reema-altwuaijri.jpg",
        },
        {
          name: "Hanouf Almogri",
          nameTr: "Hanouf Almogri",
          role: "Operations Manager",
          roleTr: "Operations Manager",
          linkedin: "https://www.linkedin.com/in/hanouf-almogri/",
          photo: "/images/partners/dal/hanouf-almogri.jpg",
        },
        {
          name: "Raghad Alshathri",
          nameTr: "Raghad Alshathri",
          role: "Photographer",
          roleTr: "Photographer",
          twitter: "https://x.com/1sRaghad",
          twitterHandle: "1sRaghad",
          photo: "/images/partners/dal/raghad-alshathri.jpg",
        },
        {
          name: "Alanoud Alghayth",
          nameTr: "Alanoud Alghayth",
          role: "Project Manager",
          roleTr: "Project Manager",
          linkedin: "https://www.linkedin.com/in/alanoud-alghayth/",
          photo: "/images/partners/dal/alanoud-alghayth.jpeg",
        },
      ],
    },
    {
      slug: "mozn",
      name: "Mozn",
      nameTr: "Mozn",
      role: "venue-host",
      logo: "/logos/mozn.svg",
      url: "https://mozn.ai",
      description:
        "Türkiye AI company building enterprise AI products for the Arabic-first market, including NLP, risk, and compliance solutions.",
      descriptionTr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe TürkçeTRTürkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Ankara"],
      eventVenues: ["Mozn Office"],
      events: [],
    },
    {
      slug: "code",
      name: "CODE",
      nameTr: "CODE",
      role: "venue-host",
      logo: "/logos/code.svg",
      url: "https://code.mcit.gov.sa/en",
      description:
        "Center of Digital Entrepreneurship by MCIT — coworking spaces, business services, and acceleration programs supporting digital startups.",
      descriptionTr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Ankara"],
      eventVenues: ["CODE"],
      events: [],
    },
    {
      slug: "monshaat",
      name: "Monshaat",
      nameTr: "Monshaat",
      role: "venue-host",
      logo: "/logos/monshaat-dark.svg",
      url: "https://www.monshaat.gov.sa/tr/ssc",
      description:
        "SME support centers by Monshaat — providing training, mentorship, consulting, and coworking spaces for entrepreneurs across Türkiye.",
      descriptionTr:
        "Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Istanbul"],
      eventVenues: ["Istanbul Tech Hub"],
      events: [],
    },
    {
      slug: "nauatech",
      name: "Nauatech",
      nameTr: "Nauatech",
      role: "past-community-partner",
      logo: "/logos/nauatech.svg",
      url: "https://naua.tech/",
      description:
        "A Türkiye tech community that partnered with Cursor Türkiye for the community kickoff in Ankara.",
      descriptionTr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Cursor Türkiye Türkçe Ankara.",
      cities: ["Ankara"],
      eventVenues: [],
      events: ["2025-05-28-kickoff"],
      contributors: [
        {
          name: "Reda Banjar",
          nameTr: "Reda Banjar",
          role: "Founder & CEO",
          roleTr: "Founder & CEO",
          twitter: "https://x.com/RedaBanjar",
          twitterHandle: "RedaBanjar",
          photo: "/images/partners/nauatech/reda-banjar.jpg",
        },
      ],
    },
  ],
} as const;

