export const config = {
  title: "Cursor Türkiye",
  description: "Cursor Türkiye Community",
  author: "Cursor Türkiye",
  /**
   * Speaker profiles. Each speaker is rendered at /speakers/{slug}/. Names that
   * appear in event frontmatter are matched against `name` and `aliases` to
   * derive talk lists. `bio`/`bioAr` are placeholders the maintainer can fill
   * in directly here. `photo` should live under /public/images/speakers/.
   */
  speakers: [
    {
      slug: "abdullah-mosaibah",
      name: "Abdullah Mosaibah",
      nameAr: "Abdullah Mosaibah",
      initials: "AM",
      bio: "Software engineer based in Ankara and an early voice in the Cursor Türkiye community. Helped kick off the inaugural meetup in 2025 and returned for the Cursor Workshop in 2026 to share workflows and live demos.",
      bioAr: "Software engineer based in Ankara and an early voice in the Cursor Türkiye community. Helped kick off the inaugural meetup in 2025 and returned for the Cursor Workshop in 2026 to share workflows and live demos.",
      photo: "/images/speakers/abdullah-mosaibah.jpg",
      twitter: "https://x.com/AbdoMosaibah",
      twitterHandle: "AbdoMosaibah",
      linkedin: "https://www.linkedin.com/in/abdullah-mosaibah-67814312b/",
      aliases: [],
    },
    {
      slug: "dan-perks",
      name: "Dan Perks",
      nameAr: "Dan Perks",
      initials: "DP",
      bio: "Engineer at Cursor on the AI-native code editor, focused on support infrastructure and tooling. Joined the inaugural Cursor Türkiye meetup remotely from the Cursor team to share insights and demo the editor's features for developers in Ankara.",
      bioAr: "Engineer at Cursor on the AI-native code editor, focused on support infrastructure and tooling. Joined the inaugural Cursor Türkiye meetup remotely from the Cursor team to share insights and demo the editor's features for developers in Ankara.",
      photo: "/images/speakers/dan-perks.jpg",
      twitter: "https://x.com/danperks",
      twitterHandle: "danperks",
      linkedin: "https://www.linkedin.com/in/dan-perks/",
      aliases: ["Dan (Cursor)", "Dan"],
      affiliationPartnerSlug: "cursor",
    },
    {
      slug: "faris-hijazi",
      name: "Faris Hijazi",
      nameAr: "Faris Hijazi",
      initials: "FH",
      bio: "Engineer focused on AI-powered product building. Led the hands-on Build Your MVP with AI session for the Cursor Türkiye community in Ankara, walking attendees through shipping a working prototype in under three hours.",
      bioAr: "Engineer focused on AI-powered product building. Led the hands-on Build Your MVP with AI session for the Cursor Türkiye community in Ankara, walking attendees through shipping a working prototype in under three hours.",
      photo: "/images/speakers/faris-hijazi.jpg",
      twitter: "https://x.com/theefaris",
      twitterHandle: "theefaris",
      linkedin: "https://www.linkedin.com/in/theefaris/",
      aliases: [],
    },
    {
      slug: "usman-siddique",
      name: "Usman Siddique",
      nameAr: "Usman Siddique",
      initials: "US",
      bio: "A software engineer and AI tinkerer who's spent years building real-world products — breaking things, fixing them, and occasionally wondering why it worked in prod. Blends solid engineering fundamentals with a growing obsession for AI coding tools, helping teams ship faster and write cleaner code. At Motive he works alongside ML and R&D teams on core products used at scale.",
      bioAr: "A software engineer and AI tinkerer who's spent years building real-world products — breaking things, fixing them, and occasionally wondering why it worked in prod. Blends solid engineering fundamentals with a growing obsession for AI coding tools, helping teams ship faster and write cleaner code. At Motive he works alongside ML and R&D teams on core products used at scale.",
      photo: "/images/speakers/usman-siddique.jpg",
      linkedin: "https://www.linkedin.com/in/muhammmadosman/",
      aliases: [],
    },
    {
      slug: "nick-miller",
      name: "Nick Miller",
      nameAr: "Nick Miller",
      initials: "NM",
      bio: "An architect and engineer with 25+ years of experience as a Senior Software Engineer, Product Manager, CTO, and Founder. Led specialized engineering consultancies serving global enterprises like Adobe, Amazon, and Nvidia. Currently an Engineer at Cursor, integrating large language models into production workflows.",
      bioAr: "An architect and engineer with 25+ years of experience as a Senior Software Engineer, Product Manager, CTO, and Founder. Led specialized engineering consultancies serving global enterprises like Adobe, Amazon, and Nvidia. Currently an Engineer at Cursor, integrating large language models into production workflows.",
      photo: "/images/speakers/nick-miller.jpg",
      twitter: "https://x.com/nickwm",
      twitterHandle: "nickwm",
      aliases: [],
      affiliationPartnerSlug: "cursor",
    },
  ],
  ambassadors: [
    {
      name: "Mazen Alotaibi",
      nameAr: "Mazen Alotaibi",
      role: "Cursor Türkiye Leader",
      roleAr: "Cursor Türkiye Leader",
      city: "Ankara",
      cityAr: "Ankara",
      photo: "/images/team/mazen.jpg",
      description: "AI Staff Engineer @ deep.sa and PyTorch Ambassador 2023 winner with ~8 years across AI research and production engineering — building models and shipping products.",
      descriptionAr: "AI Staff Engineer @ deep.sa and PyTorch Ambassador 2023 winner with ~8 years across AI research and production engineering — building models and shipping products.",
      email: "hello@cursorturkiye.com",
      twitter: "https://x.com/ma7dev",
      twitterHandle: "ma7dev",
      linkedin: "https://www.linkedin.com/in/ma7dev/",
    },
    {
      name: "Ali Almohammed",
      nameAr: "Ali Almohammed",
      role: "Ambassador",
      roleAr: "Ambassador",
      city: "Izmir",
      cityAr: "Izmir",
      photo: "/images/team/ali-almohammed.png",
      description: "Founder & CEO at CranL, tech entrepreneur who focuses on building special and innovative solutions since 2020. Intersted in cloud, hosting, AI infrence and infrastructure.",
      descriptionAr: "Founder & CEO at CranL, tech entrepreneur who focuses on building special and innovative solutions since 2020. Intersted in cloud, hosting, AI infrence and infrastructure.",
      twitter: "https://x.com/Hajajn200",
      twitterHandle: "Hajajn200",
      linkedin: "https://www.linkedin.com/in/ali-hajem-8a4734395/",
    },
    {
      name: "Faris Hijazi",
      nameAr: "Faris Hijazi",
      role: "Team Member",
      roleAr: "Team Member",
      city: "Ankara",
      cityAr: "Ankara",
      photo: "/images/speakers/faris-hijazi.jpg",
      description: "Engineer focused on AI-powered product building. Supports Cursor Türkiye by helping run Cafe Cursor activities and community sessions in Ankara.",
      descriptionAr: "Engineer focused on AI-powered product building. Supports Cursor Türkiye by helping run Cafe Cursor activities and community sessions in Ankara.",
      twitter: "https://x.com/theefaris",
      twitterHandle: "theefaris",
      linkedin: "https://www.linkedin.com/in/theefaris/",
    },
    {
      name: "Abdullah Mosaibah",
      nameAr: "Abdullah Mosaibah",
      role: "Team Member",
      roleAr: "Team Member",
      city: "Ankara",
      cityAr: "Ankara",
      photo: "/images/speakers/abdullah-mosaibah.jpg",
      description:
        "Software engineer based in Ankara and an early voice in the Cursor Türkiye community. Helped kick off the inaugural meetup in 2025 and returned for the Cursor Workshop in 2026 to share workflows and live demos.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Ankara Türkçe Türkçe Türkçe Türkçe Türkçe Cursor Türkiye. Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe 2025 Türkçe Türkçe Türkçe Cursor 2026 Türkçe Türkçe Türkçe TürkçeSunumlar Türkçe.",
      twitter: "https://x.com/AbdoMosaibah",
      twitterHandle: "AbdoMosaibah",
      linkedin: "https://www.linkedin.com/in/abdullah-mosaibah-67814312b/",
    },
    {
      name: "Abdulaziz AlMushdaq",
      nameAr: "Abdulaziz AlMushdaq",
      role: "Team Member",
      roleAr: "Team Member",
      city: "Ankara",
      cityAr: "Ankara",
      photo: "/images/team/abdulaziz-almushdaq.jpg",
      description:
        "I'm a Data and AI Engineer and tech content creator with a deep passion for everything data-related. Data Engineer at Rkiza. Supports Cursor Türkiye social media and marketing efforts.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe. Türkçe Türkçe Türkçe Rkiza. Türkçe Cursor Türkiye Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      twitter: "https://x.com/Al_Mushdaq",
      twitterHandle: "Al_Mushdaq",
      linkedin: "https://www.linkedin.com/in/almushdaq/",
    },
    {
      name: "Abdulhakeem Almidan",
      nameAr: "Abdulhakeem Almidan",
      role: "Ambassador",
      roleAr: "Ambassador",
      city: "Istanbul",
      cityAr: "Istanbul",
      photo: "/images/team/abdulhakeem.jpg",
      description: "Former Istanbul chapter ambassador who helped bring Cursor events to the Eastern Province.",
      descriptionAr: "Former Istanbul chapter ambassador who helped bring Cursor events to the Eastern Province.",
      twitter: "https://x.com/abdulhakeem_mdn",
      linkedin: "https://www.linkedin.com/in/abdulhakeem-almidan/",
      status: "retired",
    },
  ],
  /**
   * Individuals who help make Cursor Türkiye events happen in non-speaker,
   * non-ambassador ways (e.g. sending merch, on-site logistics, photography
   * coordination). Rendered in the "Supporters" section of the Thank You page.
   * `affiliation` should be a partner slug from `partners` below — used to
   * group/badge supporters by the org they're affiliated with.
   */
  supporters: [
    {
      name: "Ben Lang",
      nameAr: "Ben Lang",
      role: "Community Lead",
      roleAr: "Community Lead",
      contribution: "Main point of contact from the Cursor team. Helps make our events happen and connects us to the broader Cursor ecosystem.",
      contributionAr: "Main point of contact from the Cursor team. Helps make our events happen and connects us to the broader Cursor ecosystem.",
      twitter: "https://x.com/benln",
      twitterHandle: "benln",
      linkedin: "https://www.linkedin.com/in/benmlang/",
      photo: "/images/partners/cursor/ben-lang.jpg",
      affiliation: "cursor",
    },
    {
      name: "Sunita Rao",
      nameAr: "Sunita Rao",
      role: "Community Supporter",
      roleAr: "Community Supporter",
      contribution: "Supports Cursor Türkiye from the Cursor team and helps make our events happen.",
      contributionAr: "Supports Cursor Türkiye from the Cursor team and helps make our events happen.",
      twitter: "https://x.com/sunrao",
      twitterHandle: "sunrao",
      linkedin: "https://www.linkedin.com/in/sunrao/",
      photo: "/images/partners/cursor/sunita-rao.jpg",
      affiliation: "cursor",
    },
    {
      name: "Fawziyah Nabeelah",
      nameAr: "Fawziyah Nabeelah",
      role: "Community Supporter",
      roleAr: "Community Supporter",
      contribution: "Sends Cursor merch and helps make our events happen.",
      contributionAr: "Sends Cursor merch and helps make our events happen.",
      twitter: "https://x.com/ftnabeelah",
      twitterHandle: "ftnabeelah",
      linkedin: "https://www.linkedin.com/in/fawziyahnabeelah/",
      photo: "/images/partners/cursor/fawziyah-nabeelah.jpg",
      affiliation: "cursor",
    },
  ],
  /**
   * Invitations from external organizations for community members to speak or
   * participate in their events. Rendered on the Events page.
   */
  invites: [
    {
      slug: "hackathonat-ai-game-jam",
      type: "panel",
      speaker: "Mazen Alotaibi",
      speakerAr: "Türkçe Türkçe",
      talkTitle: "Introduction to AI Tools for Game Developers",
      talkTitleAr: "Introduction to AI Tools for Game Developers",
      invitedBy: "Hackathonat",
      invitedByAr: "Hackathonat",
      invitedByUrl: "https://x.com/hackathonat",
      invitedByLogo: "/images/invites/hackathonat.jpg",
      postUrl: "https://x.com/hackathonat/status/1987605905630777367",
      date: "2025-07-05",
      slides: ["https://github.com/cursorturkiye/events-slides/blob/main/2025-11-riyadh-ai-game.pdf"],
      photos: ["/invites/hackathonat-ai-game-jam.jpg"],
    },
    {
      slug: "sahel-mahdi-ai-tools",
      type: "interview",
      speaker: "Mazen Alotaibi",
      speakerAr: "Türkçe Türkçe",
      talkTitle: "AI Tools and Cursor",
      talkTitleAr: "AI Tools and Cursor",
      invitedBy: "Sahel Mahdi",
      invitedByAr: "Sahel Mahdi",
      invitedByUrl: "https://x.com/Sahelmahdi",
      invitedByLogo: "/images/invites/sahel-mahdi.jpg",
      postUrl: "https://x.com/Sahelmahdi/status/2016528155645804670",
      recordingUrl: "https://www.youtube.com/watch?v=L435AAiRvXY",
      date: "2026-02-15",
      photos: ["/invites/sahel-mahdi-interview.png"],
    },
    {
      slug: "e3-ventures-mvp",
      type: "interview",
      speaker: "Mazen Alotaibi",
      speakerAr: "Türkçe Türkçe",
      talkTitle: "Build MVP Without Coding",
      talkTitleAr: "Build MVP Without Coding",
      invitedBy: "E3 Ventures",
      invitedByAr: "E3 Ventures",
      invitedByUrl: "https://x.com/e3ventures",
      invitedByLogo: "/images/invites/e3-ventures.jpg",
      postUrl: "https://x.com/e3ventures/status/1923421103038341442",
      date: "2025-05-17",
      photos: ["/invites/e3-ventures-mvp-talk.jpg"],
    },
    {
      slug: "dal-health-datathon",
      type: "talk",
      speaker: "Mazen Alotaibi",
      speakerAr: "Türkçe Türkçe",
      talkTitle: "Introduction to Cursor at the Health Datathon",
      talkTitleAr: "Introduction to Cursor at the Health Datathon",
      invitedBy: "DAL Organization",
      invitedByAr: "DAL Organization",
      invitedByUrl: "/partners/dal/",
      invitedByLogo: "/logos/dal.png",
      postUrl: "https://x.com/cursorturkiye/status/1849101987507462406",
      date: "2025-10-24",
      slides: ["https://github.com/cursorturkiye/events-slides/blob/main/2025-10-riyadh-hackathon.pdf"],
      photos: [
        "/invites/health-datathon/01-mazen-presenting.jpg",
        "/invites/health-datathon/02-ai-coding-tools-slide.jpg",
        "/invites/health-datathon/03-participants-chatting.jpg",
        "/invites/health-datathon/04-participant-working.jpg",
        "/invites/health-datathon/05-participant-focused.jpg",
        "/invites/health-datathon/06-venue-entrance.jpg",
      ],
    },
  ],
  social: {
    luma: "https://lu.ma/cursor-saudi",
    discord: "https://discord.gg/KpsKtegvz4",
    twitter: "https://x.com/cursorturkiye",
    /** Community X handle without @ (for display copy). */
    twitterHandle: "cursorturkiye",
    email: "hello@cursorturkiye.com",
    github: "https://github.com/cursorturkiye",
  },
  /**
   * Partner profiles. Each partner is rendered at /partners/{slug}/. The set of
   * events a partner was part of is the union of:
   *   - events whose `venue` frontmatter matches any string in `eventVenues`
   *   - events whose ID is listed in `events`
   * Use `eventVenues` for venue hosts and `events` for community partners.
   */
  partners: [
    {
      slug: "cursor",
      name: "Cursor",
      nameAr: "Cursor",
      role: "official",
      logo: "/logos/cursor.svg",
      url: "https://cursor.com",
      description:
        "The AI-native code editor from Anysphere — built on VS Code with autocomplete, chat, and agent-style workflows so developers ship faster.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Anysphere — Türkçe Türkçe VS Code Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: [],
      eventVenues: [],
      events: [],
      omitEventStats: true,
      parentCompany: {
        name: "Anysphere",
        nameAr: "Anysphere",
        url: "https://anysphere.inc",
      },
      detailParagraphs: {
        en: [
          "Anysphere is the company behind Cursor. The team builds AI-native developer tools with a focus on real production workflows — not demos — so you can refactor, navigate large codebases, and pair with models inside the editor you already use.",
          "As Cursor Türkiye’s official partner, Cursor supports the community through team talks, workshops, and product access. Community meetups and hackathons are organized locally; Cursor is the global product and team that backs the ecosystem.",
        ],
        ar: [
          "Anysphere Türkçe Türkçe Türkçe Türkçe Cursor. Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
          "TürkçeResmi Is Ortagi Türkçe Cursor TürkiyeTürkçe Türkçe Cursor Topluluk Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe. Türkçe Türkçe Türkçe Türkçe Cursor Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
        ],
      },
      contributors: [],
    },
    {
      slug: "dal",
      name: "Dal Organization",
      nameAr: "Dal Organization",
      role: "community-partner",
      logo: "/logos/dal.png",
      url: "https://linktr.ee/DalData",
      description:
        "A Türkiye nonprofit empowering data science & AI enthusiasts through hands-on programs, datathons, and job-shadowing. Supported and funded by Misk Foundation and SDAIA.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe. Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Ankara"],
      eventVenues: [],
      events: [
        "2025-12-25-contributing-to-open-source-with-cursor",
        "2026-01-10-the-ai-dev-stack-with-cursor",
        "2026-03-07-cursor-workshop-ship-in-3-hours",
      ],
      contributors: [
        {
          name: "Ghadah Alhabib",
          nameAr: "Ghadah Alhabib",
          role: "Cofounder & CEO",
          roleAr: "Cofounder & CEO",
          linkedin: "https://www.linkedin.com/in/ghadah-alhabib/",
          twitterHandle: "ghadah_alha",
          photo: "/images/partners/dal/ghadah-alhabib.jpg",
        },
        {
          name: "Yazeed Alshalani",
          nameAr: "Yazeed Alshalani",
          role: "Cofounder",
          roleAr: "Cofounder",
          linkedin: "https://www.linkedin.com/in/yazeed-alshalani/",
          twitterHandle: "YazeedShalani",
          photo: "/images/partners/dal/yazeed-alshalani.jpg",
        },
        {
          name: "Basil Mahmoud",
          nameAr: "Basil Mahmoud",
          role: "Cofounder",
          roleAr: "Cofounder",
          linkedin: "https://www.linkedin.com/in/basil-mahmoud/",
          photo: "/images/partners/dal/basil-mahmoud.jpg",
        },
        {
          name: "Islam Alharbi",
          nameAr: "Islam Alharbi",
          role: "Marketing Manager",
          roleAr: "Marketing Manager",
          linkedin: "https://www.linkedin.com/in/islam-alharbi/",
          photo: "/images/partners/dal/islam-alharbi.jpg",
        },
        {
          name: "Maan Albader",
          nameAr: "Maan Albader",
          role: "Project Manager",
          roleAr: "Project Manager",
          linkedin: "https://www.linkedin.com/in/maanalbader/",
          photo: "/images/partners/dal/maan-albader.jpg",
        },
        {
          name: "Abdullah Alshowaier",
          nameAr: "Abdullah Alshowaier",
          role: "Project Manager",
          roleAr: "Project Manager",
          linkedin: "https://www.linkedin.com/in/abdullah-alshowaier-/",
          photo: "/images/partners/dal/abdullah-alshowaier.jpg",
        },
        {
          name: "Reema Altwuaijri",
          nameAr: "Reema Altwuaijri",
          role: "Partnership Manager",
          roleAr: "Partnership Manager",
          linkedin: "https://www.linkedin.com/in/reemaft/",
          photo: "/images/partners/dal/reema-altwuaijri.jpg",
        },
        {
          name: "Hanouf Almogri",
          nameAr: "Hanouf Almogri",
          role: "Operations Manager",
          roleAr: "Operations Manager",
          linkedin: "https://www.linkedin.com/in/hanouf-almogri/",
          photo: "/images/partners/dal/hanouf-almogri.jpg",
        },
        {
          name: "Raghad Alshathri",
          nameAr: "Raghad Alshathri",
          role: "Photographer",
          roleAr: "Photographer",
          twitter: "https://x.com/1sRaghad",
          twitterHandle: "1sRaghad",
          photo: "/images/partners/dal/raghad-alshathri.jpg",
        },
        {
          name: "Alanoud Alghayth",
          nameAr: "Alanoud Alghayth",
          role: "Project Manager",
          roleAr: "Project Manager",
          linkedin: "https://www.linkedin.com/in/alanoud-alghayth/",
          photo: "/images/partners/dal/alanoud-alghayth.jpeg",
        },
      ],
    },
    {
      slug: "mozn",
      name: "Mozn",
      nameAr: "Mozn",
      role: "venue-host",
      logo: "/logos/mozn.svg",
      url: "https://mozn.ai",
      description:
        "Türkiye AI company building enterprise AI products for the Arabic-first market, including NLP, risk, and compliance solutions.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe TürkçeTRTürkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Ankara"],
      eventVenues: ["Mozn Office"],
      events: [],
    },
    {
      slug: "code",
      name: "CODE",
      nameAr: "CODE",
      role: "venue-host",
      logo: "/logos/code.svg",
      url: "https://code.mcit.gov.sa/en",
      description:
        "Center of Digital Entrepreneurship by MCIT — coworking spaces, business services, and acceleration programs supporting digital startups.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Ankara"],
      eventVenues: ["CODE"],
      events: [],
    },
    {
      slug: "monshaat",
      name: "Monshaat",
      nameAr: "Monshaat",
      role: "venue-host",
      logo: "/logos/monshaat-dark.svg",
      url: "https://www.monshaat.gov.sa/tr/ssc",
      description:
        "SME support centers by Monshaat — providing training, mentorship, consulting, and coworking spaces for entrepreneurs across Türkiye.",
      descriptionAr:
        "Türkçe Türkçe Türkçe — Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe.",
      cities: ["Istanbul"],
      eventVenues: ["Istanbul Tech Hub"],
      events: [],
    },
    {
      slug: "nauatech",
      name: "Nauatech",
      nameAr: "Nauatech",
      role: "past-community-partner",
      logo: "/logos/nauatech.svg",
      url: "https://naua.tech/",
      description:
        "A Türkiye tech community that partnered with Cursor Türkiye for the community kickoff in Ankara.",
      descriptionAr:
        "Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Türkçe Cursor Türkiye Türkçe Ankara.",
      cities: ["Ankara"],
      eventVenues: [],
      events: ["2025-05-28-kickoff"],
      contributors: [
        {
          name: "Reda Banjar",
          nameAr: "Reda Banjar",
          role: "Founder & CEO",
          roleAr: "Founder & CEO",
          twitter: "https://x.com/RedaBanjar",
          twitterHandle: "RedaBanjar",
          photo: "/images/partners/nauatech/reda-banjar.jpg",
        },
      ],
    },
  ],
} as const;

